#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "Usage: $0 input output"
	exit 1
fi

if [ ! -e "$1" ]; then
	echo "Input file $1 does not exist!" >& 2
	exit 1
fi

rm -f $2
printf "/*\n" >> $2
printf " * This file was generated by $0\n" $0 >> $2
printf " */\n\n" >> $2
printf "const char *create_basileus_db_str = \"\\\n" >> $2
tr -s "[:cntrl:]" " " < $1 >> $2
printf "\";" >> $2
